-- 청파 같이: 알림 확장 + 1:1 쪽지 + 활동 24시간 전 알림
-- 운영 Supabase SQL Editor에서 한 번 실행합니다.
-- 기존 notifications 테이블을 유지하면서 필요한 구조만 추가합니다.

begin;

create table if not exists public.direct_messages (
  id bigint generated by default as identity primary key,
  sender_id uuid not null references public.profiles(id) on delete cascade,
  recipient_id uuid not null references public.profiles(id) on delete cascade,
  content text not null check (char_length(btrim(content)) between 1 and 2000),
  created_at timestamptz not null default now(),
  read_at timestamptz,
  constraint direct_messages_not_self check (sender_id <> recipient_id)
);

create index if not exists direct_messages_recipient_created_idx
  on public.direct_messages(recipient_id, created_at desc);
create index if not exists direct_messages_sender_created_idx
  on public.direct_messages(sender_id, created_at desc);

alter table public.direct_messages enable row level security;

-- 직접 INSERT/UPDATE 대신 SECURITY DEFINER RPC를 사용합니다.
revoke insert, update, delete on public.direct_messages from anon, authenticated;
grant select on public.direct_messages to authenticated;

-- 자신이 보낸 쪽지 또는 자신이 받은 쪽지만 조회할 수 있습니다.
do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'direct_messages' and policyname = 'direct_messages_select_own'
  ) then
    create policy direct_messages_select_own
      on public.direct_messages
      for select
      to authenticated
      using (auth.uid() = sender_id or auth.uid() = recipient_id);
  end if;
end $$;

-- 기존 notifications에 확장 메타데이터를 추가합니다.
alter table public.notifications
  add column if not exists kind text not null default 'system',
  add column if not exists message_id bigint references public.direct_messages(id) on delete set null,
  add column if not exists target_path text,
  add column if not exists expires_at timestamptz,
  add column if not exists dedupe_key text;

create unique index if not exists notifications_user_dedupe_unique
  on public.notifications(user_id, dedupe_key)
  where dedupe_key is not null;

create index if not exists notifications_user_created_idx
  on public.notifications(user_id, created_at desc);
create index if not exists notifications_user_expires_idx
  on public.notifications(user_id, expires_at);

-- 쪽지 전송: 쪽지 저장과 상대방 알림 생성을 하나의 트랜잭션으로 처리합니다.
create or replace function public.send_direct_message(
  p_recipient_id uuid,
  p_content text
)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  v_sender_id uuid := auth.uid();
  v_content text := btrim(coalesce(p_content, ''));
  v_message_id bigint;
  v_sender_name text;
begin
  if v_sender_id is null then
    raise exception '로그인이 필요합니다.';
  end if;

  if p_recipient_id is null or p_recipient_id = v_sender_id then
    raise exception '쪽지를 받을 회원을 확인해 주세요.';
  end if;

  if char_length(v_content) < 1 or char_length(v_content) > 2000 then
    raise exception '쪽지는 1자 이상 2000자 이하로 작성해 주세요.';
  end if;

  if not exists (
    select 1 from public.profiles p
    where p.id = v_sender_id and p.status = 'approved'
  ) then
    raise exception '승인된 회원만 쪽지를 보낼 수 있습니다.';
  end if;

  if not exists (
    select 1 from public.profiles p
    where p.id = p_recipient_id and p.status = 'approved'
  ) then
    raise exception '쪽지를 받을 수 없는 회원입니다.';
  end if;

  select coalesce(p.display_name, '회원')
    into v_sender_name
  from public.profiles p
  where p.id = v_sender_id;

  insert into public.direct_messages(sender_id, recipient_id, content)
  values (v_sender_id, p_recipient_id, v_content)
  returning id into v_message_id;

  insert into public.notifications(
    user_id,
    title,
    body,
    is_read,
    created_at,
    kind,
    message_id,
    target_path,
    dedupe_key
  )
  values (
    p_recipient_id,
    v_sender_name || '님의 쪽지',
    left(v_content, 120),
    false,
    now(),
    'direct_message',
    v_message_id,
    null,
    'direct_message:' || v_message_id::text
  );

  return v_message_id;
end;
$$;

revoke all on function public.send_direct_message(uuid, text) from public;
grant execute on function public.send_direct_message(uuid, text) to authenticated;

create or replace function public.mark_direct_message_read(p_message_id bigint)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  update public.direct_messages
  set read_at = coalesce(read_at, now())
  where id = p_message_id
    and recipient_id = auth.uid();
end;
$$;

revoke all on function public.mark_direct_message_read(bigint) from public;
grant execute on function public.mark_direct_message_read(bigint) to authenticated;

-- 새 활동 등록 알림: 등록 시점부터 2일 동안 현재 알림, 이후 지난 알림으로 분류됩니다.
create or replace function public.notify_new_activity()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if new.status is distinct from 'cancelled' then
    insert into public.notifications(
      user_id,
      title,
      body,
      event_id,
      is_read,
      created_at,
      kind,
      target_path,
      expires_at,
      dedupe_key
    )
    select
      p.id,
      '새로운 활동이 등록됐어요',
      new.title,
      new.id,
      false,
      now(),
      'new_activity',
      '#/activities/' || new.id::text,
      now() + interval '2 days',
      'new_activity:' || new.id::text
    from public.profiles p
    where p.status = 'approved'
    on conflict (user_id, dedupe_key) where dedupe_key is not null do nothing;
  end if;
  return new;
end;
$$;

drop trigger if exists trg_notify_new_activity on public.events;
create trigger trg_notify_new_activity
after insert on public.events
for each row execute function public.notify_new_activity();

-- 내가 참여 확정(joined)한 활동이 24시간 안에 시작하면 알림을 한 번만 생성합니다.
-- GitHub Pages는 서버 스케줄러가 없으므로 앱이 열려 있을 때 1분마다 호출하고,
-- 앱 재접속 시에도 즉시 호출하여 누락된 알림을 보완합니다.
create or replace function public.sync_my_activity_reminders()
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user_id uuid := auth.uid();
  v_created integer := 0;
begin
  if v_user_id is null then
    return 0;
  end if;

  with candidates as (
    select
      e.id,
      e.title,
      ((e.event_date::date + coalesce(e.start_time::time, time '00:00')) at time zone 'Asia/Seoul') as starts_at
    from public.event_participants ep
    join public.events e on e.id = ep.event_id
    where ep.user_id = v_user_id
      and ep.status = 'joined'
      and e.status in ('scheduled', 'closed')
  ), inserted as (
    insert into public.notifications(
      user_id,
      title,
      body,
      event_id,
      is_read,
      created_at,
      kind,
      target_path,
      expires_at,
      dedupe_key
    )
    select
      v_user_id,
      '참여 활동이 곧 시작해요',
      c.title || ' · 24시간 이내 시작',
      c.id,
      false,
      now(),
      'activity_reminder',
      '#/activities/' || c.id::text,
      c.starts_at,
      'activity_reminder:' || c.id::text
    from candidates c
    where c.starts_at > now()
      and c.starts_at <= now() + interval '24 hours'
    on conflict (user_id, dedupe_key) where dedupe_key is not null do nothing
    returning 1
  )
  select count(*) into v_created from inserted;

  return v_created;
end;
$$;

revoke all on function public.sync_my_activity_reminders() from public;
grant execute on function public.sync_my_activity_reminders() to authenticated;

-- notifications INSERT를 브라우저에서 즉시 받을 수 있도록 Realtime publication에 등록합니다.
do $$
begin
  if not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'notifications'
  ) then
    alter publication supabase_realtime add table public.notifications;
  end if;
end $$;

commit;
