export const STORAGE_KEYS = Object.freeze({ playerKey: "liar_player_key", nickname: "liar_nickname", room: "liar_current_room" });
export const CATEGORIES = Object.freeze(["음식", "장소", "직업", "동물", "물건", "인물", "스포츠", "교통수단", "자연", "취미", "음악", "기타"]);
export const GAME_MODE = Object.freeze({ CLASSIC:"classic", DRAWING_SPY:"drawing_spy" });
export const ROUND_STATUS = Object.freeze({ ROLE_REVEAL: "ROLE_REVEAL", SPEAKING: "SPEAKING", DRAWING:"DRAWING", DISCUSSION: "DISCUSSION", VOTING: "VOTING", RUNOFF_VOTING: "RUNOFF_VOTING", VOTE_RESULT: "VOTE_RESULT", LIAR_REVEAL: "LIAR_REVEAL", LIAR_GUESS: "LIAR_GUESS", ROUND_RESULT: "ROUND_RESULT" });
export const MIN_READY_PLAYERS = 4;
export const MAX_ROOM_PLAYERS = 12;
export const MIN_CITIZENS = 2;
export const ERROR_MESSAGES = Object.freeze({
  NOT_CURRENT_SPEAKER:"현재 발언자만 다음 발언자로 넘길 수 있습니다.", INVALID_GUESS_TEXT:"추측할 제시어를 입력해 주세요.", NOT_LIAR:"라이어만 제시어를 추측할 수 있습니다.", GUESS_LIMIT_REACHED:"제시어 추측 기회를 모두 사용했습니다.",
  AUTH_REQUIRED:"로그인 세션이 만료되었습니다. 다시 로그인해 주세요.", AUTH_CONTEXT_CHANGED:"계정이 변경되어 이전 요청 결과를 취소했습니다.", ROUND_PARTICIPANT_CANNOT_LEAVE:"라운드 진행 중에는 방에서 나갈 수 없습니다. 라운드가 끝난 뒤 다시 시도해 주세요.", PLAYER_KEY_CONFLICT:"게임 접속 정보를 갱신하지 못했습니다. 다시 시도해 주세요.", ROOM_NOT_FOUND:"방을 찾을 수 없습니다.", ROOM_EXPIRED:"만료된 방입니다.", ROOM_FULL:"방 정원이 가득 찼습니다.", ALREADY_IN_ACTIVE_ROOM:"현재 참여 중인 방이 있습니다. 기존 방으로 돌아가거나 방에서 나온 뒤 새 방을 이용해 주세요.", NOT_ROOM_MEMBER:"이 방의 참가자가 아닙니다.", NOT_HOST:"방장만 할 수 있습니다.", INVALID_ROOM_STATE:"현재 방 상태에서는 실행할 수 없습니다.", INVALID_GAME_STATE:"현재 게임 상태에서는 실행할 수 없습니다.", INVALID_ROUND_STATE:"현재 라운드 상태에서는 실행할 수 없습니다.", NOT_ENOUGH_READY_PLAYERS:"준비한 참가자가 4명 이상이어야 합니다.", INVALID_LIAR_COUNT:"최소 2명의 시민이 있도록 라이어 수를 설정해 주세요.", ROLE_NOT_CONFIRMED:"모든 참가자가 역할을 확인해야 합니다.", STALE_VERSION:"상태가 변경되었습니다. 최신 상태를 확인한 뒤 다시 시도해 주세요.", WORD_POOL_EMPTY:"조건에 맞는 제시어가 없습니다.", INVALID_NICKNAME:"닉네임은 1~20자로 입력해 주세요.", SPEAKER_INDEX_OUT_OF_RANGE:"더 이동할 발언자가 없습니다.", SPEAKING_NOT_FINISHED:"마지막 발언자까지 진행해 주세요.", INVALID_GAME_SETTINGS:"게임 설정을 확인해 주세요.", TOO_MANY_READY_PLAYERS:"준비 인원은 최대 12명입니다.", NOT_ROUND_PARTICIPANT:"이번 라운드 참가자가 아닙니다.", VOTE_ALREADY_STARTED:"이미 투표가 시작되었습니다.", INVALID_BALLOT_SELECTION_COUNT:"정확한 인원의 후보를 선택해 주세요.", INVALID_VOTE_CANDIDATE:"선택할 수 없는 투표 후보입니다.", SELF_VOTE_NOT_ALLOWED:"본인에게는 투표할 수 없습니다.", VOTE_NOT_ALL_SUBMITTED:"모든 라운드 참가자가 투표해야 마감할 수 있습니다.", VOTE_NOT_STARTED:"아직 투표가 시작되지 않았습니다.", VOTE_CLOSED:"이미 마감된 투표입니다.", RUNOFF_NOT_REQUIRED:"재투표가 필요하지 않습니다.", INVALID_RUNOFF_STATE:"재투표 상태가 올바르지 않습니다.", INVALID_FINAL_SUSPECT_COUNT:"최종 의심자 수가 올바르지 않습니다.", RESULT_LIAR_REVEAL_REQUIRED:"라이어를 공개한 뒤 다음 라운드 또는 새 게임을 진행해 주세요.", RESULT_LIARS_ALREADY_REVEALED:"이미 라이어가 공개되었습니다.",
  INVALID_DRAWING_STROKE:"그림 선 정보를 처리할 수 없습니다.", INVALID_DRAWING_STATE:"현재 그림 진행 상태를 확인해 주세요.", DRAWING_TIME_EXPIRED:"그림 시간이 종료되었습니다. 다음 차례로 이동합니다.", DRAWING_STROKE_LIMIT_REACHED:"사용할 수 있는 획을 모두 사용했습니다.", NOT_CURRENT_DRAWER:"현재 그림 차례인 사용자만 그릴 수 있습니다.",
  INVALID_CUSTOM_WORD_PACK:"커스텀 제시어는 5~200개를 입력해 주세요. 각 제시어는 1~100자여야 합니다.", INVALID_CUSTOM_WORD_PACK_NAME:"커스텀 팩 이름은 1~40자로 입력해 주세요.", CUSTOM_WORD_PACK_REQUIRED:"사용할 커스텀 제시어 팩을 선택해 주세요.", CUSTOM_WORD_PACK_NOT_FOUND:"커스텀 제시어 팩을 찾을 수 없습니다.", CUSTOM_WORD_PACK_NAME_TAKEN:"같은 이름의 커스텀 제시어 팩이 이미 있습니다.", DUPLICATE_CUSTOM_WORD:"같은 의미로 인식되는 중복 제시어가 있습니다. 중복 항목을 제거해 주세요.", CUSTOM_WORD_PACK_LIMIT:"커스텀 제시어 팩은 계정당 최대 20개까지 저장할 수 있습니다.", CUSTOM_WORD_PACK_IN_USE:"현재 게임에서 사용 중인 팩입니다. 기본 제시어로 변경한 뒤 삭제해 주세요."
});
export const escapeHTML = (value="") => String(value).replace(/[&<>'"]/g,(char)=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"})[char]);
