import { escapeHTML } from "../constants.js";

const peopleList=(people=[])=>people.length?`<ul>${people.map(person=>`<li>${escapeHTML(person.nickname)}</li>`).join("")}</ul>`:"";

export function voteView(s,voteState,myBallot,isHost){
 const seats=Number(voteState?.seats_to_fill||0);const selected=new Set(myBallot||[]);const submitted=voteState?.has_submitted===true;
 const candidates=voteState?.candidates||[];const locked=voteState?.locked_winners||[];const participant=voteState?.is_round_participant===true;const complete=Number(voteState?.submitted_count)===Number(voteState?.required_count);
 const runoff=voteState?.kind==="runoff";const title=runoff?`재투표 ${Math.max(1,Number(voteState?.stage_no||2)-1)}`:"투표";
 return `<section class="card stack vote-panel"><h2>${title}</h2><p>${runoff?`동률 후보 중 ${seats}명을 선택하세요.`:"라이어로 의심되는 사람을 선택하세요."}</p>${runoff&&locked.length?`<div><h3>확정된 의심 후보</h3>${peopleList(locked)}</div>`:""}${runoff?"<h3>재투표 후보</h3>":""}${participant?`<p class="notice"><strong>${seats}명</strong>을 선택해야 합니다.</p><form class="stack" data-action="ballot"><div class="vote-candidates">${candidates.map(candidate=>`<label class="vote-candidate ${candidate.is_me?"disabled":""}"><input type="checkbox" name="target" value="${escapeHTML(candidate.round_player_id)}" ${selected.has(candidate.round_player_id)?"checked":""} ${candidate.is_me?"disabled":""}><span>${escapeHTML(candidate.nickname)}${candidate.is_me?" (본인) - 선택 불가":""}</span></label>`).join("")}</div><p>현재 선택: <strong data-vote-selected>${selected.size}</strong> / ${seats}</p><button type="submit" data-ballot-submit ${selected.size!==seats?"disabled":""}>${submitted?"투표 수정":"투표하기"}</button></form>`:`<p class="notice">이번 라운드 관전자는 투표할 수 없습니다.</p>`}<div class="stack"><h3>투표 진행</h3><p><strong>${voteState?.submitted_count||0} / ${voteState?.required_count||0}명 완료</strong></p>${isHost?`<button data-action="close-vote" ${complete?"":"disabled"}>투표 마감</button>`:""}</div></section>`;
}

export function voteResultView(voteState,isHost){
 const tally=voteState?.tally||[];const runoff=voteState?.runoff_required===true;const boundary=voteState?.boundary_candidates||[];const locked=voteState?.locked_winners||[];const finalSuspects=voteState?.final_suspects||[];
 return `<section class="card stack"><h2>투표 결과</h2><ol class="vote-results">${tally.map(item=>`<li><strong>${escapeHTML(item.nickname)}</strong><span>${Number(item.votes)||0}표</span></li>`).join("")}</ol>${runoff?`<div class="stack"><h3>동률이 발생했습니다.</h3><p>아래 후보를 대상으로 재투표가 필요합니다.</p>${locked.length?`<div><h3>확정된 의심 후보</h3>${peopleList(locked)}</div>`:""}<div><h3>재투표 후보</h3>${peopleList(boundary)}</div><p>남은 자리: <strong>${Number(voteState?.remaining_seats)||0}명</strong></p>${isHost?'<div class="row"><button class="secondary" data-action="start-runoff-speaking">한 바퀴 더 발언 후 재투표</button><button data-action="start-runoff">바로 재투표</button></div>':'<p class="notice">방장이 다음 진행 방식을 선택할 때까지 기다려 주세요.</p>'}</div>`:finalSuspects.length?`<div><h3>최종 의심자</h3>${peopleList(finalSuspects)}<p class="notice">라이어 검거 판정은 다음 단계에서 진행됩니다.</p></div>`:'<p class="notice">투표 결과를 확인할 수 없습니다.</p>'}</section>`;
}