-- Liar Game initial word seed. Run after schema.sql.
-- The 140 words below are the complete requirements.md baseline (20 per category).
-- normalized_word is explicitly stored after Unicode NFC, trim, and removal of
-- all whitespace; these baseline Korean strings contain no removable whitespace.
-- Re-running this file synchronizes word, difficulty, and enabled with this seed.

insert into public.liar_words (category, word, normalized_word, difficulty, enabled)
values
  ('음식', '떡볶이', '떡볶이', 'easy', true),
  ('음식', '김치찌개', '김치찌개', 'easy', true),
  ('음식', '삼겹살', '삼겹살', 'easy', true),
  ('음식', '치킨', '치킨', 'easy', true),
  ('음식', '피자', '피자', 'easy', true),
  ('음식', '햄버거', '햄버거', 'easy', true),
  ('음식', '라면', '라면', 'easy', true),
  ('음식', '초밥', '초밥', 'easy', true),
  ('음식', '냉면', '냉면', 'normal', true),
  ('음식', '비빔밥', '비빔밥', 'normal', true),
  ('음식', '파스타', '파스타', 'easy', true),
  ('음식', '짜장면', '짜장면', 'easy', true),
  ('음식', '붕어빵', '붕어빵', 'normal', true),
  ('음식', '마라탕', '마라탕', 'normal', true),
  ('음식', '돈가스', '돈가스', 'normal', true),
  ('음식', '족발', '족발', 'normal', true),
  ('음식', '김밥', '김밥', 'easy', true),
  ('음식', '샌드위치', '샌드위치', 'normal', true),
  ('음식', '샤브샤브', '샤브샤브', 'hard', true),
  ('음식', '아이스크림', '아이스크림', 'easy', true),

  ('장소', '학교', '학교', 'easy', true),
  ('장소', '병원', '병원', 'easy', true),
  ('장소', '공항', '공항', 'easy', true),
  ('장소', '놀이공원', '놀이공원', 'easy', true),
  ('장소', 'PC방', 'PC방', 'easy', true),
  ('장소', '노래방', '노래방', 'easy', true),
  ('장소', '찜질방', '찜질방', 'normal', true),
  ('장소', '편의점', '편의점', 'easy', true),
  ('장소', '도서관', '도서관', 'easy', true),
  ('장소', '영화관', '영화관', 'easy', true),
  ('장소', '수영장', '수영장', 'normal', true),
  ('장소', '헬스장', '헬스장', 'normal', true),
  ('장소', '지하철역', '지하철역', 'normal', true),
  ('장소', '휴게소', '휴게소', 'normal', true),
  ('장소', '웨딩홀', '웨딩홀', 'hard', true),
  ('장소', '대형마트', '대형마트', 'normal', true),
  ('장소', '미용실', '미용실', 'easy', true),
  ('장소', '카페', '카페', 'easy', true),
  ('장소', '교회', '교회', 'normal', true),
  ('장소', '캠핑장', '캠핑장', 'normal', true),

  ('직업', '의사', '의사', 'easy', true),
  ('직업', '간호사', '간호사', 'easy', true),
  ('직업', '교사', '교사', 'easy', true),
  ('직업', '경찰', '경찰', 'easy', true),
  ('직업', '소방관', '소방관', 'easy', true),
  ('직업', '요리사', '요리사', 'easy', true),
  ('직업', '개발자', '개발자', 'normal', true),
  ('직업', '디자이너', '디자이너', 'normal', true),
  ('직업', '변호사', '변호사', 'easy', true),
  ('직업', '기자', '기자', 'normal', true),
  ('직업', '배우', '배우', 'easy', true),
  ('직업', '가수', '가수', 'easy', true),
  ('직업', '운동선수', '운동선수', 'normal', true),
  ('직업', '미용사', '미용사', 'normal', true),
  ('직업', '택시기사', '택시기사', 'normal', true),
  ('직업', '사진작가', '사진작가', 'normal', true),
  ('직업', '유튜버', '유튜버', 'normal', true),
  ('직업', '파일럿', '파일럿', 'hard', true),
  ('직업', '약사', '약사', 'normal', true),
  ('직업', '목수', '목수', 'hard', true),

  ('동물', '강아지', '강아지', 'easy', true),
  ('동물', '고양이', '고양이', 'easy', true),
  ('동물', '사자', '사자', 'easy', true),
  ('동물', '호랑이', '호랑이', 'easy', true),
  ('동물', '기린', '기린', 'easy', true),
  ('동물', '코끼리', '코끼리', 'easy', true),
  ('동물', '원숭이', '원숭이', 'easy', true),
  ('동물', '토끼', '토끼', 'easy', true),
  ('동물', '펭귄', '펭귄', 'easy', true),
  ('동물', '돌고래', '돌고래', 'normal', true),
  ('동물', '상어', '상어', 'easy', true),
  ('동물', '악어', '악어', 'easy', true),
  ('동물', '캥거루', '캥거루', 'normal', true),
  ('동물', '판다', '판다', 'easy', true),
  ('동물', '알파카', '알파카', 'hard', true),
  ('동물', '낙타', '낙타', 'normal', true),
  ('동물', '수달', '수달', 'normal', true),
  ('동물', '고슴도치', '고슴도치', 'normal', true),
  ('동물', '부엉이', '부엉이', 'normal', true),
  ('동물', '두더지', '두더지', 'hard', true),

  ('물건', '스마트폰', '스마트폰', 'easy', true),
  ('물건', '노트북', '노트북', 'easy', true),
  ('물건', '우산', '우산', 'easy', true),
  ('물건', '이어폰', '이어폰', 'easy', true),
  ('물건', '가방', '가방', 'easy', true),
  ('물건', '시계', '시계', 'easy', true),
  ('물건', '칫솔', '칫솔', 'easy', true),
  ('물건', '냉장고', '냉장고', 'easy', true),
  ('물건', '전자레인지', '전자레인지', 'normal', true),
  ('물건', '리모컨', '리모컨', 'easy', true),
  ('물건', '선풍기', '선풍기', 'easy', true),
  ('물건', '카메라', '카메라', 'easy', true),
  ('물건', '키보드', '키보드', 'normal', true),
  ('물건', '마우스', '마우스', 'normal', true),
  ('물건', '지갑', '지갑', 'easy', true),
  ('물건', '안경', '안경', 'easy', true),
  ('물건', '충전기', '충전기', 'normal', true),
  ('물건', '텀블러', '텀블러', 'hard', true),
  ('물건', '드라이기', '드라이기', 'normal', true),
  ('물건', '가위', '가위', 'easy', true),

  ('인물', '세종대왕', '세종대왕', 'easy', true),
  ('인물', '이순신', '이순신', 'easy', true),
  ('인물', '손흥민', '손흥민', 'easy', true),
  ('인물', '아이유', '아이유', 'easy', true),
  ('인물', '유재석', '유재석', 'easy', true),
  ('인물', '봉준호', '봉준호', 'normal', true),
  ('인물', '백종원', '백종원', 'easy', true),
  ('인물', '김연아', '김연아', 'easy', true),
  ('인물', '박지성', '박지성', 'normal', true),
  ('인물', '싸이', '싸이', 'easy', true),
  ('인물', '안중근', '안중근', 'normal', true),
  ('인물', '신사임당', '신사임당', 'normal', true),
  ('인물', '장영실', '장영실', 'hard', true),
  ('인물', '강호동', '강호동', 'easy', true),
  ('인물', '전지현', '전지현', 'normal', true),
  ('인물', '공유', '공유', 'normal', true),
  ('인물', '마동석', '마동석', 'normal', true),
  ('인물', '박찬욱', '박찬욱', 'hard', true),
  ('인물', '류현진', '류현진', 'normal', true),
  ('인물', '페이커', '페이커', 'normal', true),

  ('기타', '크리스마스', '크리스마스', 'easy', true),
  ('기타', '여름휴가', '여름휴가', 'normal', true),
  ('기타', '생일', '생일', 'easy', true),
  ('기타', '수학여행', '수학여행', 'normal', true),
  ('기타', '첫눈', '첫눈', 'normal', true),
  ('기타', '시험기간', '시험기간', 'normal', true),
  ('기타', '운동회', '운동회', 'normal', true),
  ('기타', '소개팅', '소개팅', 'hard', true),
  ('기타', '야근', '야근', 'normal', true),
  ('기타', '캠핑', '캠핑', 'easy', true),
  ('기타', '데이트', '데이트', 'easy', true),
  ('기타', '졸업식', '졸업식', 'normal', true),
  ('기타', '결혼식', '결혼식', 'easy', true),
  ('기타', '월요일', '월요일', 'easy', true),
  ('기타', '주말', '주말', 'easy', true),
  ('기타', '장마', '장마', 'normal', true),
  ('기타', '벚꽃', '벚꽃', 'normal', true),
  ('기타', '다이어트', '다이어트', 'normal', true),
  ('기타', '택배', '택배', 'easy', true),
  ('기타', '출근', '출근', 'easy', true)
on conflict (category, normalized_word) do update
set word = excluded.word,
    difficulty = excluded.difficulty,
    enabled = excluded.enabled,
    updated_at = now();
