-- Splendor Phase 4: server-authoritative token taking and excess return.
-- Applied to Supabase as:
--   1) splendor_phase4_token_actions
--   2) splendor_phase4_action_log_policy

alter table public.splendor_games
  add column if not exists turn_phase text not null default 'action';

alter table public.splendor_games
  add column if not exists last_action_at timestamptz;

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conname = 'splendor_games_turn_phase_check'
      and conrelid = 'public.splendor_games'::regclass
  ) then
    alter table public.splendor_games
      add constraint splendor_games_turn_phase_check
      check (turn_phase in ('action','return_excess'));
  end if;
end $$;

create table if not exists public.splendor_action_log (
  id bigint generated by default as identity primary key,
  game_id uuid not null references public.splendor_games(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  client_action_id uuid not null,
  action_type text not null check (action_type in ('take_distinct','take_double','return_excess')),
  payload jsonb not null default '{}'::jsonb check (jsonb_typeof(payload) = 'object'),
  game_version_after bigint not null,
  created_at timestamptz not null default now(),
  unique (game_id, client_action_id)
);

create index if not exists splendor_action_log_game_created_idx
  on public.splendor_action_log(game_id, created_at desc);

alter table public.splendor_action_log enable row level security;
revoke all on public.splendor_action_log from anon, authenticated;

drop policy if exists "splendor no direct action log reads" on public.splendor_action_log;
create policy "splendor no direct action log reads"
on public.splendor_action_log
for select
to authenticated
using (false);

create or replace function private.splendor_token_total(p_tokens jsonb)
returns integer
language sql
immutable
set search_path = ''
as $$
  select
      coalesce((p_tokens ->> 'white')::integer, 0)
    + coalesce((p_tokens ->> 'blue')::integer, 0)
    + coalesce((p_tokens ->> 'green')::integer, 0)
    + coalesce((p_tokens ->> 'red')::integer, 0)
    + coalesce((p_tokens ->> 'black')::integer, 0)
    + coalesce((p_tokens ->> 'gold')::integer, 0);
$$;

revoke all on function private.splendor_token_total(jsonb) from public, anon, authenticated;

create or replace function private.splendor_next_active_seat(p_game_id uuid, p_current_seat smallint)
returns smallint
language sql
stable
security definer
set search_path = ''
as $$
  select coalesce(
    (
      select gp.seat
      from public.splendor_game_players gp
      where gp.game_id = p_game_id
        and gp.status = 'active'
        and gp.seat > p_current_seat
      order by gp.seat
      limit 1
    ),
    (
      select gp.seat
      from public.splendor_game_players gp
      where gp.game_id = p_game_id
        and gp.status = 'active'
      order by gp.seat
      limit 1
    )
  );
$$;

revoke all on function private.splendor_next_active_seat(uuid, smallint) from public, anon, authenticated;

create or replace function private.splendor_game_snapshot(p_game_id uuid)
returns jsonb
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
  v_result jsonb;
begin
  if not private.splendor_is_game_member(p_game_id) then
    return null;
  end if;

  select jsonb_build_object(
    'game', jsonb_build_object(
      'id', g.id,
      'room_id', g.room_id,
      'room_code', r.room_code,
      'ruleset_key', g.ruleset_key,
      'status', g.status,
      'version', g.version,
      'turn_no', g.turn_no,
      'turn_phase', g.turn_phase,
      'starting_player_seat', g.starting_player_seat,
      'current_turn_seat', g.current_turn_seat,
      'bank_tokens', g.bank_tokens,
      'target_score', g.target_score,
      'max_tokens', g.max_tokens,
      'max_reserved', g.max_reserved,
      'started_at', g.started_at,
      'last_action_at', g.last_action_at
    ),
    'players', coalesce((
      select jsonb_agg(
        jsonb_build_object(
          'id', gp.id,
          'user_id', gp.user_id,
          'nickname', gp.nickname,
          'seat', gp.seat,
          'score', gp.score,
          'tokens', gp.tokens,
          'token_count', private.splendor_token_total(gp.tokens),
          'bonuses', gp.bonuses,
          'purchased_card_count', gp.purchased_card_count,
          'reserved_card_count', gp.reserved_card_count,
          'is_current_turn', gp.seat = g.current_turn_seat
        ) order by gp.seat
      )
      from public.splendor_game_players gp
      where gp.game_id = g.id and gp.status = 'active'
    ), '[]'::jsonb),
    'self', (
      select jsonb_build_object(
        'id', gp.id,
        'user_id', gp.user_id,
        'nickname', gp.nickname,
        'seat', gp.seat,
        'score', gp.score,
        'tokens', gp.tokens,
        'token_count', private.splendor_token_total(gp.tokens),
        'must_return_count', case
          when gp.seat = g.current_turn_seat and g.turn_phase = 'return_excess'
            then greatest(private.splendor_token_total(gp.tokens) - g.max_tokens, 0)
          else 0
        end,
        'bonuses', gp.bonuses,
        'purchased_card_count', gp.purchased_card_count,
        'reserved_card_count', gp.reserved_card_count,
        'is_current_turn', gp.seat = g.current_turn_seat
      )
      from public.splendor_game_players gp
      where gp.game_id = g.id
        and gp.user_id = (select auth.uid())
      limit 1
    ),
    'cards', coalesce((
      select jsonb_agg(
        jsonb_build_object(
          'instance_id', gc.id,
          'card_key', cc.card_key,
          'tier', cc.tier,
          'slot', gc.face_up_slot,
          'bonus', cc.bonus_color,
          'prestige', cc.prestige,
          'cost', cc.cost,
          'title', cc.title,
          'image_path', cc.image_path
        ) order by cc.tier desc, gc.face_up_slot
      )
      from public.splendor_game_cards gc
      join public.splendor_card_catalog cc on cc.id = gc.catalog_card_id
      where gc.game_id = g.id and gc.location = 'face_up'
    ), '[]'::jsonb),
    'decks', jsonb_build_object(
      '1', (select count(*) from public.splendor_game_cards gc where gc.game_id = g.id and gc.tier = 1 and gc.location = 'deck'),
      '2', (select count(*) from public.splendor_game_cards gc where gc.game_id = g.id and gc.tier = 2 and gc.location = 'deck'),
      '3', (select count(*) from public.splendor_game_cards gc where gc.game_id = g.id and gc.tier = 3 and gc.location = 'deck')
    ),
    'nobles', coalesce((
      select jsonb_agg(
        jsonb_build_object(
          'instance_id', gn.id,
          'noble_key', nc.noble_key,
          'prestige', nc.prestige,
          'requirements', nc.requirements,
          'title', nc.title,
          'image_path', nc.image_path,
          'display_order', gn.display_order,
          'status', gn.status
        ) order by gn.display_order
      )
      from public.splendor_game_nobles gn
      join public.splendor_noble_catalog nc on nc.id = gn.catalog_noble_id
      where gn.game_id = g.id
    ), '[]'::jsonb)
  ) into v_result
  from public.splendor_games g
  join public.splendor_rooms r on r.id = g.room_id
  where g.id = p_game_id;

  return v_result;
end;
$$;

revoke all on function private.splendor_game_snapshot(uuid) from public, anon, authenticated;

create or replace function public.splendor_take_distinct(
  p_room_id uuid,
  p_colors text[],
  p_expected_version bigint,
  p_client_action_id uuid
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_user_id uuid := (select auth.uid());
  v_game public.splendor_games%rowtype;
  v_player public.splendor_game_players%rowtype;
  v_existing public.splendor_action_log%rowtype;
  v_color text;
  v_choice_count integer;
  v_distinct_count integer;
  v_available_color_count integer;
  v_bank jsonb;
  v_tokens jsonb;
  v_bank_count integer;
  v_player_count integer;
  v_total_after integer;
  v_next_seat smallint;
  v_new_version bigint;
begin
  if v_user_id is null or not private.is_approved_member() then
    raise exception 'AUTH_REQUIRED' using errcode = 'P0001';
  end if;
  if p_client_action_id is null then
    raise exception 'INVALID_ACTION_ID' using errcode = 'P0001';
  end if;
  if not private.splendor_is_room_member(p_room_id) then
    raise exception 'PLAYER_NOT_MEMBER' using errcode = 'P0001';
  end if;

  select * into v_game
  from public.splendor_games
  where room_id = p_room_id
  for update;

  if not found or v_game.status <> 'playing' then
    raise exception 'GAME_NOT_STARTED' using errcode = 'P0001';
  end if;

  select * into v_existing
  from public.splendor_action_log
  where game_id = v_game.id and client_action_id = p_client_action_id;

  if found then
    if v_existing.user_id = v_user_id and v_existing.action_type = 'take_distinct' then
      return private.splendor_game_snapshot(v_game.id);
    end if;
    raise exception 'ACTION_ID_REUSED' using errcode = 'P0001';
  end if;

  if v_game.version <> p_expected_version then
    raise exception 'STATE_CHANGED' using errcode = 'P0001';
  end if;
  if v_game.turn_phase <> 'action' then
    raise exception 'RETURN_TOKENS_REQUIRED' using errcode = 'P0001';
  end if;

  select * into v_player
  from public.splendor_game_players
  where game_id = v_game.id and user_id = v_user_id and status = 'active'
  for update;

  if not found then
    raise exception 'PLAYER_NOT_MEMBER' using errcode = 'P0001';
  end if;
  if v_player.seat <> v_game.current_turn_seat then
    raise exception 'NOT_YOUR_TURN' using errcode = 'P0001';
  end if;

  v_choice_count := coalesce(array_length(p_colors, 1), 0);
  if v_choice_count < 1 or v_choice_count > 3 then
    raise exception 'INVALID_TOKEN_SELECTION' using errcode = 'P0001';
  end if;

  select count(distinct c) into v_distinct_count from unnest(p_colors) as c;
  if v_distinct_count <> v_choice_count then
    raise exception 'TOKENS_MUST_BE_DISTINCT' using errcode = 'P0001';
  end if;

  if exists (
    select 1 from unnest(p_colors) as c
    where c is null or c not in ('white','blue','green','red','black')
  ) then
    raise exception 'INVALID_TOKEN_COLOR' using errcode = 'P0001';
  end if;

  select count(*) into v_available_color_count
  from (values ('white'),('blue'),('green'),('red'),('black')) as colors(color)
  where coalesce((v_game.bank_tokens ->> color)::integer, 0) > 0;

  if v_available_color_count = 0 then
    raise exception 'NO_GEMS_AVAILABLE' using errcode = 'P0001';
  end if;
  if v_available_color_count >= 3 and v_choice_count <> 3 then
    raise exception 'MUST_TAKE_THREE_DIFFERENT' using errcode = 'P0001';
  end if;
  if v_available_color_count < 3 and v_choice_count > v_available_color_count then
    raise exception 'INVALID_TOKEN_SELECTION' using errcode = 'P0001';
  end if;

  v_bank := v_game.bank_tokens;
  v_tokens := v_player.tokens;

  foreach v_color in array p_colors loop
    v_bank_count := coalesce((v_bank ->> v_color)::integer, 0);
    if v_bank_count < 1 then
      raise exception 'GEM_UNAVAILABLE' using errcode = 'P0001';
    end if;
    v_player_count := coalesce((v_tokens ->> v_color)::integer, 0);
    v_bank := jsonb_set(v_bank, array[v_color], to_jsonb(v_bank_count - 1), true);
    v_tokens := jsonb_set(v_tokens, array[v_color], to_jsonb(v_player_count + 1), true);
  end loop;

  update public.splendor_game_players
  set tokens = v_tokens
  where id = v_player.id;

  v_total_after := private.splendor_token_total(v_tokens);
  if v_total_after > v_game.max_tokens then
    update public.splendor_games
    set bank_tokens = v_bank,
        turn_phase = 'return_excess',
        version = version + 1,
        last_action_at = now()
    where id = v_game.id
    returning version into v_new_version;
  else
    v_next_seat := private.splendor_next_active_seat(v_game.id, v_game.current_turn_seat);
    update public.splendor_games
    set bank_tokens = v_bank,
        current_turn_seat = v_next_seat,
        turn_phase = 'action',
        turn_no = turn_no + 1,
        version = version + 1,
        last_action_at = now()
    where id = v_game.id
    returning version into v_new_version;
  end if;

  insert into public.splendor_action_log(game_id, user_id, client_action_id, action_type, payload, game_version_after)
  values (v_game.id, v_user_id, p_client_action_id, 'take_distinct', jsonb_build_object('colors', to_jsonb(p_colors)), v_new_version);

  return private.splendor_game_snapshot(v_game.id);
end;
$$;

create or replace function public.splendor_take_double(
  p_room_id uuid,
  p_color text,
  p_expected_version bigint,
  p_client_action_id uuid
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_user_id uuid := (select auth.uid());
  v_game public.splendor_games%rowtype;
  v_player public.splendor_game_players%rowtype;
  v_existing public.splendor_action_log%rowtype;
  v_color text := lower(btrim(coalesce(p_color, '')));
  v_bank jsonb;
  v_tokens jsonb;
  v_bank_count integer;
  v_player_count integer;
  v_total_after integer;
  v_next_seat smallint;
  v_new_version bigint;
begin
  if v_user_id is null or not private.is_approved_member() then
    raise exception 'AUTH_REQUIRED' using errcode = 'P0001';
  end if;
  if p_client_action_id is null then
    raise exception 'INVALID_ACTION_ID' using errcode = 'P0001';
  end if;
  if not private.splendor_is_room_member(p_room_id) then
    raise exception 'PLAYER_NOT_MEMBER' using errcode = 'P0001';
  end if;

  select * into v_game
  from public.splendor_games
  where room_id = p_room_id
  for update;

  if not found or v_game.status <> 'playing' then
    raise exception 'GAME_NOT_STARTED' using errcode = 'P0001';
  end if;

  select * into v_existing
  from public.splendor_action_log
  where game_id = v_game.id and client_action_id = p_client_action_id;

  if found then
    if v_existing.user_id = v_user_id and v_existing.action_type = 'take_double' then
      return private.splendor_game_snapshot(v_game.id);
    end if;
    raise exception 'ACTION_ID_REUSED' using errcode = 'P0001';
  end if;

  if v_game.version <> p_expected_version then
    raise exception 'STATE_CHANGED' using errcode = 'P0001';
  end if;
  if v_game.turn_phase <> 'action' then
    raise exception 'RETURN_TOKENS_REQUIRED' using errcode = 'P0001';
  end if;
  if v_color not in ('white','blue','green','red','black') then
    raise exception 'INVALID_TOKEN_COLOR' using errcode = 'P0001';
  end if;

  select * into v_player
  from public.splendor_game_players
  where game_id = v_game.id and user_id = v_user_id and status = 'active'
  for update;

  if not found then
    raise exception 'PLAYER_NOT_MEMBER' using errcode = 'P0001';
  end if;
  if v_player.seat <> v_game.current_turn_seat then
    raise exception 'NOT_YOUR_TURN' using errcode = 'P0001';
  end if;

  v_bank_count := coalesce((v_game.bank_tokens ->> v_color)::integer, 0);
  if v_bank_count < 4 then
    raise exception 'DOUBLE_REQUIRES_FOUR' using errcode = 'P0001';
  end if;

  v_player_count := coalesce((v_player.tokens ->> v_color)::integer, 0);
  v_bank := jsonb_set(v_game.bank_tokens, array[v_color], to_jsonb(v_bank_count - 2), true);
  v_tokens := jsonb_set(v_player.tokens, array[v_color], to_jsonb(v_player_count + 2), true);

  update public.splendor_game_players
  set tokens = v_tokens
  where id = v_player.id;

  v_total_after := private.splendor_token_total(v_tokens);
  if v_total_after > v_game.max_tokens then
    update public.splendor_games
    set bank_tokens = v_bank,
        turn_phase = 'return_excess',
        version = version + 1,
        last_action_at = now()
    where id = v_game.id
    returning version into v_new_version;
  else
    v_next_seat := private.splendor_next_active_seat(v_game.id, v_game.current_turn_seat);
    update public.splendor_games
    set bank_tokens = v_bank,
        current_turn_seat = v_next_seat,
        turn_phase = 'action',
        turn_no = turn_no + 1,
        version = version + 1,
        last_action_at = now()
    where id = v_game.id
    returning version into v_new_version;
  end if;

  insert into public.splendor_action_log(game_id, user_id, client_action_id, action_type, payload, game_version_after)
  values (v_game.id, v_user_id, p_client_action_id, 'take_double', jsonb_build_object('color', v_color), v_new_version);

  return private.splendor_game_snapshot(v_game.id);
end;
$$;

create or replace function public.splendor_return_excess(
  p_room_id uuid,
  p_returns jsonb,
  p_expected_version bigint,
  p_client_action_id uuid
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_user_id uuid := (select auth.uid());
  v_game public.splendor_games%rowtype;
  v_player public.splendor_game_players%rowtype;
  v_existing public.splendor_action_log%rowtype;
  v_tokens jsonb;
  v_bank jsonb;
  v_color text;
  v_amount integer;
  v_owned integer;
  v_bank_count integer;
  v_excess integer;
  v_return_total integer := 0;
  v_next_seat smallint;
  v_new_version bigint;
begin
  if v_user_id is null or not private.is_approved_member() then
    raise exception 'AUTH_REQUIRED' using errcode = 'P0001';
  end if;
  if p_client_action_id is null then
    raise exception 'INVALID_ACTION_ID' using errcode = 'P0001';
  end if;
  if not private.splendor_is_room_member(p_room_id) then
    raise exception 'PLAYER_NOT_MEMBER' using errcode = 'P0001';
  end if;

  select * into v_game
  from public.splendor_games
  where room_id = p_room_id
  for update;

  if not found or v_game.status <> 'playing' then
    raise exception 'GAME_NOT_STARTED' using errcode = 'P0001';
  end if;

  select * into v_existing
  from public.splendor_action_log
  where game_id = v_game.id and client_action_id = p_client_action_id;

  if found then
    if v_existing.user_id = v_user_id and v_existing.action_type = 'return_excess' then
      return private.splendor_game_snapshot(v_game.id);
    end if;
    raise exception 'ACTION_ID_REUSED' using errcode = 'P0001';
  end if;

  if v_game.version <> p_expected_version then
    raise exception 'STATE_CHANGED' using errcode = 'P0001';
  end if;
  if v_game.turn_phase <> 'return_excess' then
    raise exception 'NO_RETURN_REQUIRED' using errcode = 'P0001';
  end if;

  select * into v_player
  from public.splendor_game_players
  where game_id = v_game.id and user_id = v_user_id and status = 'active'
  for update;

  if not found then
    raise exception 'PLAYER_NOT_MEMBER' using errcode = 'P0001';
  end if;
  if v_player.seat <> v_game.current_turn_seat then
    raise exception 'NOT_YOUR_TURN' using errcode = 'P0001';
  end if;

  v_excess := private.splendor_token_total(v_player.tokens) - v_game.max_tokens;
  if v_excess <= 0 then
    raise exception 'NO_RETURN_REQUIRED' using errcode = 'P0001';
  end if;
  if p_returns is null or jsonb_typeof(p_returns) <> 'object' then
    raise exception 'INVALID_RETURN_SELECTION' using errcode = 'P0001';
  end if;
  if exists (
    select 1 from jsonb_object_keys(p_returns) as k
    where k not in ('white','blue','green','red','black','gold')
  ) then
    raise exception 'INVALID_TOKEN_COLOR' using errcode = 'P0001';
  end if;
  if exists (
    select 1 from jsonb_each_text(p_returns) as e(key, value)
    where value !~ '^[0-9]+$'
  ) then
    raise exception 'INVALID_RETURN_SELECTION' using errcode = 'P0001';
  end if;

  select coalesce(sum(value::integer), 0) into v_return_total
  from jsonb_each_text(p_returns) as e(key, value);

  if v_return_total <> v_excess then
    raise exception 'RETURN_COUNT_MISMATCH' using errcode = 'P0001';
  end if;

  v_tokens := v_player.tokens;
  v_bank := v_game.bank_tokens;

  for v_color, v_amount in
    select key, value::integer from jsonb_each_text(p_returns)
  loop
    if v_amount < 0 then
      raise exception 'INVALID_RETURN_SELECTION' using errcode = 'P0001';
    end if;
    if v_amount = 0 then
      continue;
    end if;
    v_owned := coalesce((v_tokens ->> v_color)::integer, 0);
    if v_amount > v_owned then
      raise exception 'RETURN_MORE_THAN_OWNED' using errcode = 'P0001';
    end if;
    v_bank_count := coalesce((v_bank ->> v_color)::integer, 0);
    v_tokens := jsonb_set(v_tokens, array[v_color], to_jsonb(v_owned - v_amount), true);
    v_bank := jsonb_set(v_bank, array[v_color], to_jsonb(v_bank_count + v_amount), true);
  end loop;

  update public.splendor_game_players
  set tokens = v_tokens
  where id = v_player.id;

  v_next_seat := private.splendor_next_active_seat(v_game.id, v_game.current_turn_seat);
  update public.splendor_games
  set bank_tokens = v_bank,
      current_turn_seat = v_next_seat,
      turn_phase = 'action',
      turn_no = turn_no + 1,
      version = version + 1,
      last_action_at = now()
  where id = v_game.id
  returning version into v_new_version;

  insert into public.splendor_action_log(game_id, user_id, client_action_id, action_type, payload, game_version_after)
  values (v_game.id, v_user_id, p_client_action_id, 'return_excess', jsonb_build_object('returns', p_returns), v_new_version);

  return private.splendor_game_snapshot(v_game.id);
end;
$$;

revoke all on function public.splendor_take_distinct(uuid, text[], bigint, uuid) from public, anon;
revoke all on function public.splendor_take_double(uuid, text, bigint, uuid) from public, anon;
revoke all on function public.splendor_return_excess(uuid, jsonb, bigint, uuid) from public, anon;
grant execute on function public.splendor_take_distinct(uuid, text[], bigint, uuid) to authenticated;
grant execute on function public.splendor_take_double(uuid, text, bigint, uuid) to authenticated;
grant execute on function public.splendor_return_excess(uuid, jsonb, bigint, uuid) to authenticated;
