create table public.client_error_logs (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references public.profiles(id) on delete cascade,
  error_kind text not null check (error_kind in ('runtime','unhandled','page','api')),
  message text not null check (char_length(message) between 1 and 500),
  route text not null default '/' check (char_length(route) <= 300),
  context jsonb not null default '{}'::jsonb check (jsonb_typeof(context) = 'object' and pg_column_size(context) <= 4096),
  created_at timestamptz not null default now()
);

create index client_error_logs_user_created_idx
  on public.client_error_logs(user_id, created_at desc);
create index client_error_logs_created_idx
  on public.client_error_logs(created_at desc);

alter table public.client_error_logs enable row level security;
revoke all on table public.client_error_logs from anon, authenticated;
grant insert, select on table public.client_error_logs to authenticated;
grant usage, select on sequence public.client_error_logs_id_seq to authenticated;

create policy client_error_logs_insert_own
on public.client_error_logs
for insert
to authenticated
with check (
  private.is_approved_member()
  and user_id = (select auth.uid())
);

create policy client_error_logs_select_admin
on public.client_error_logs
for select
to authenticated
using (private.is_admin());

create or replace function private.guard_client_error_log_insert()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_recent_count integer;
begin
  if (select auth.uid()) is null
     or new.user_id <> (select auth.uid())
     or not private.is_approved_member()
  then
    raise exception 'Approved membership required'
      using errcode = '42501';
  end if;

  select count(*)::integer
  into v_recent_count
  from public.client_error_logs as l
  where l.user_id = new.user_id
    and l.created_at >= now() - interval '1 minute';

  if v_recent_count >= 20 then
    raise exception 'Client error report rate limit exceeded'
      using errcode = '54000';
  end if;

  return new;
end;
$$;

revoke execute on function private.guard_client_error_log_insert() from public, anon, authenticated, service_role;

create trigger client_error_logs_rate_limit
before insert on public.client_error_logs
for each row execute function private.guard_client_error_log_insert();

create or replace function private.cleanup_client_error_logs()
returns integer
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_deleted integer;
begin
  delete from public.client_error_logs
  where created_at < now() - interval '30 days';
  get diagnostics v_deleted = row_count;
  return v_deleted;
end;
$$;

revoke execute on function private.cleanup_client_error_logs() from public, anon, authenticated, service_role;

select cron.schedule(
  'cheongpa-client-error-retention',
  '5 19 * * *',
  'select private.cleanup_client_error_logs();'
);
