create table if not exists public.direct_messages (
  id bigint generated by default as identity primary key,
  sender_id uuid not null references public.profiles(id) on delete cascade,
  recipient_id uuid not null references public.profiles(id) on delete cascade,
  content text not null check (char_length(btrim(content)) between 1 and 2000),
  created_at timestamptz not null default now(),
  read_at timestamptz,
  constraint direct_messages_not_self check (sender_id <> recipient_id)
);

create index if not exists direct_messages_recipient_created_idx
  on public.direct_messages(recipient_id, created_at desc);
create index if not exists direct_messages_sender_created_idx
  on public.direct_messages(sender_id, created_at desc);

alter table public.direct_messages enable row level security;
revoke insert, update, delete on public.direct_messages from anon, authenticated;
grant select on public.direct_messages to authenticated;

drop policy if exists direct_messages_select_own on public.direct_messages;
create policy direct_messages_select_own
  on public.direct_messages
  for select
  to authenticated
  using ((select auth.uid()) = sender_id or (select auth.uid()) = recipient_id);

alter table public.notifications
  add column if not exists kind text,
  add column if not exists message_id bigint references public.direct_messages(id) on delete set null,
  add column if not exists target_path text,
  add column if not exists expires_at timestamptz,
  add column if not exists dedupe_key text;

update public.notifications
set kind = notification_type
where kind is null;

alter table public.notifications
  alter column kind set default 'system',
  alter column kind set not null;

alter table public.notifications drop constraint if exists notifications_notification_type_check;
alter table public.notifications add constraint notifications_notification_type_check
  check (notification_type = any (array[
    'event_updated'::text,
    'event_cancelled'::text,
    'waitlist_promoted'::text,
    'poll_closed'::text,
    'new_activity'::text,
    'direct_message'::text,
    'activity_reminder'::text
  ]));

alter table public.notifications drop constraint if exists notification_target_check;
alter table public.notifications add constraint notification_target_check
  check (event_id is not null or poll_id is not null or message_id is not null);

create unique index if not exists notifications_user_dedupe_unique
  on public.notifications(user_id, dedupe_key)
  where dedupe_key is not null;
create index if not exists notifications_user_created_idx
  on public.notifications(user_id, created_at desc);
create index if not exists notifications_user_expires_idx
  on public.notifications(user_id, expires_at);

create or replace function public.send_direct_message(
  p_recipient_id uuid,
  p_content text
)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  v_sender_id uuid := auth.uid();
  v_content text := btrim(coalesce(p_content, ''));
  v_message_id bigint;
  v_sender_name text;
begin
  if v_sender_id is null then
    raise exception '로그인이 필요합니다.';
  end if;
  if p_recipient_id is null or p_recipient_id = v_sender_id then
    raise exception '쪽지를 받을 회원을 확인해 주세요.';
  end if;
  if char_length(v_content) < 1 or char_length(v_content) > 2000 then
    raise exception '쪽지는 1자 이상 2000자 이하로 작성해 주세요.';
  end if;
  if not exists (
    select 1 from public.profiles p
    where p.id = v_sender_id and p.status = 'approved'
  ) then
    raise exception '승인된 회원만 쪽지를 보낼 수 있습니다.';
  end if;
  if not exists (
    select 1 from public.profiles p
    where p.id = p_recipient_id and p.status = 'approved'
  ) then
    raise exception '쪽지를 받을 수 없는 회원입니다.';
  end if;

  select coalesce(p.display_name, '회원') into v_sender_name
  from public.profiles p where p.id = v_sender_id;

  insert into public.direct_messages(sender_id, recipient_id, content)
  values (v_sender_id, p_recipient_id, v_content)
  returning id into v_message_id;

  insert into public.notifications(
    user_id, notification_type, kind, title, body,
    message_id, is_read, created_at, target_path, dedupe_key
  ) values (
    p_recipient_id, 'direct_message', 'direct_message',
    v_sender_name || '님의 쪽지', left(v_content, 120),
    v_message_id, false, now(), null,
    'direct_message:' || v_message_id::text
  );

  return v_message_id;
end;
$$;

revoke all on function public.send_direct_message(uuid, text) from public;
grant execute on function public.send_direct_message(uuid, text) to authenticated;

create or replace function public.mark_direct_message_read(p_message_id bigint)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if auth.uid() is null then
    raise exception '로그인이 필요합니다.';
  end if;
  update public.direct_messages
  set read_at = coalesce(read_at, now())
  where id = p_message_id and recipient_id = auth.uid();
end;
$$;

revoke all on function public.mark_direct_message_read(bigint) from public;
grant execute on function public.mark_direct_message_read(bigint) to authenticated;

create or replace function private.notify_new_activity()
returns trigger
language plpgsql
security definer
set search_path = public, private
as $$
begin
  if new.status is distinct from 'cancelled' then
    insert into public.notifications(
      user_id, notification_type, kind, title, body,
      event_id, is_read, created_at, target_path, expires_at, dedupe_key
    )
    select
      p.id, 'new_activity', 'new_activity',
      '새로운 활동이 등록됐어요', new.title,
      new.id, false, now(), '#/activities/' || new.id::text,
      now() + interval '2 days', 'new_activity:' || new.id::text
    from public.profiles p
    where p.status = 'approved'
    on conflict (user_id, dedupe_key) where dedupe_key is not null do nothing;
  end if;
  return new;
end;
$$;

revoke all on function private.notify_new_activity() from public;

drop trigger if exists trg_notify_new_activity on public.events;
create trigger trg_notify_new_activity
  after insert on public.events
  for each row execute function private.notify_new_activity();

create or replace function public.sync_my_activity_reminders()
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user_id uuid := auth.uid();
  v_created integer := 0;
begin
  if v_user_id is null then return 0; end if;
  if not exists (
    select 1 from public.profiles p
    where p.id = v_user_id and p.status = 'approved'
  ) then return 0; end if;

  with candidates as (
    select
      e.id,
      e.title,
      ((e.event_date + e.start_time) at time zone 'Asia/Seoul') as starts_at
    from public.event_participants ep
    join public.events e on e.id = ep.event_id
    where ep.user_id = v_user_id
      and ep.status = 'joined'
      and e.status in ('scheduled', 'closed')
  ), inserted as (
    insert into public.notifications(
      user_id, notification_type, kind, title, body,
      event_id, is_read, created_at, target_path, expires_at, dedupe_key
    )
    select
      v_user_id, 'activity_reminder', 'activity_reminder',
      '참여 활동이 곧 시작해요', c.title || ' · 24시간 이내 시작',
      c.id, false, now(), '#/activities/' || c.id::text,
      c.starts_at, 'activity_reminder:' || c.id::text
    from candidates c
    where c.starts_at > now()
      and c.starts_at <= now() + interval '24 hours'
    on conflict (user_id, dedupe_key) where dedupe_key is not null do nothing
    returning 1
  )
  select count(*) into v_created from inserted;

  return v_created;
end;
$$;

revoke all on function public.sync_my_activity_reminders() from public;
grant execute on function public.sync_my_activity_reminders() to authenticated;

do $$
begin
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'notifications'
  ) then
    alter publication supabase_realtime add table public.notifications;
  end if;
end $$;
