begin;

alter table public.events
  add column if not exists organizer_id uuid;

alter table public.events disable trigger events_set_updated_at;
update public.events
set organizer_id = created_by
where organizer_id is null;
alter table public.events enable trigger events_set_updated_at;

alter table public.events
  alter column organizer_id set not null;

alter table public.events
  drop constraint if exists events_organizer_id_fkey;
alter table public.events
  add constraint events_organizer_id_fkey
  foreign key (organizer_id) references public.profiles(id);

create index if not exists idx_events_organizer_id
  on public.events(organizer_id);

create table if not exists public.event_organizer_history (
  id bigint generated by default as identity primary key,
  event_id bigint not null references public.events(id) on delete cascade,
  previous_organizer_id uuid references public.profiles(id),
  organizer_id uuid not null references public.profiles(id),
  changed_by uuid references public.profiles(id),
  change_type text not null check (change_type in ('initial', 'transfer')),
  previous_organizer_left boolean not null default false,
  changed_at timestamptz not null default now()
);

create unique index if not exists event_organizer_history_initial_once
  on public.event_organizer_history(event_id)
  where change_type = 'initial';

create index if not exists idx_event_organizer_history_event_changed_at
  on public.event_organizer_history(event_id, changed_at, id);

alter table public.event_organizer_history enable row level security;
revoke all on table public.event_organizer_history from public, anon, authenticated;
grant select on table public.event_organizer_history to service_role;

insert into public.event_organizer_history (
  event_id,
  previous_organizer_id,
  organizer_id,
  changed_by,
  change_type,
  previous_organizer_left,
  changed_at
)
select
  e.id,
  null,
  e.created_by,
  e.created_by,
  'initial',
  false,
  e.created_at
from public.events e
on conflict (event_id) where change_type = 'initial' do nothing;

create or replace function private.set_initial_event_organizer()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  new.organizer_id := new.created_by;
  return new;
end;
$$;

revoke all on function private.set_initial_event_organizer()
from public, anon, authenticated;

drop trigger if exists events_set_initial_organizer on public.events;
create trigger events_set_initial_organizer
before insert on public.events
for each row execute function private.set_initial_event_organizer();

create or replace function private.record_initial_event_organizer()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into public.event_organizer_history (
    event_id,
    previous_organizer_id,
    organizer_id,
    changed_by,
    change_type,
    previous_organizer_left,
    changed_at
  ) values (
    new.id,
    null,
    new.organizer_id,
    new.created_by,
    'initial',
    false,
    new.created_at
  );
  return new;
end;
$$;

revoke all on function private.record_initial_event_organizer()
from public, anon, authenticated;

drop trigger if exists events_record_initial_organizer on public.events;
create trigger events_record_initial_organizer
after insert on public.events
for each row execute function private.record_initial_event_organizer();

create or replace function private.record_event_organizer_transfer()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_changed_by uuid := auth.uid();
  v_previous_organizer_left boolean := coalesce(
    current_setting('app.event_organizer_previous_leaves', true),
    'false'
  ) = 'true';
begin
  if new.organizer_id is not distinct from old.organizer_id then
    return new;
  end if;

  insert into public.event_organizer_history (
    event_id,
    previous_organizer_id,
    organizer_id,
    changed_by,
    change_type,
    previous_organizer_left,
    changed_at
  ) values (
    new.id,
    old.organizer_id,
    new.organizer_id,
    v_changed_by,
    'transfer',
    v_previous_organizer_left,
    now()
  );

  return new;
end;
$$;

revoke all on function private.record_event_organizer_transfer()
from public, anon, authenticated;

drop trigger if exists events_record_organizer_transfer on public.events;
create trigger events_record_organizer_transfer
after update of organizer_id on public.events
for each row execute function private.record_event_organizer_transfer();

create or replace function private.protect_creator_identity()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_required_permission text;
  v_organizer_transfer_allowed boolean := tg_table_name = 'events'
    and coalesce(current_setting('app.allow_event_organizer_transfer', true), 'false') = 'true';
begin
  if tg_table_name = 'events' then
    if new.created_by is distinct from old.created_by then
      raise exception '최초 등록자는 변경할 수 없습니다.' using errcode = '42501';
    end if;

    if new.organizer_id is distinct from old.organizer_id
       and not v_organizer_transfer_allowed then
      raise exception '주최자는 주최자 변경 기능을 통해서만 변경할 수 있습니다.' using errcode = '42501';
    end if;

    if new.created_at is distinct from old.created_at then
      raise exception '생성일은 변경할 수 없습니다.' using errcode = '42501';
    end if;

    return new;
  end if;

  v_required_permission := case tg_table_name
    when 'event_series' then 'community'
    when 'date_polls' then 'operations'
    else null
  end;

  if auth.uid() is not null
     and (v_required_permission is null or not private.has_admin_permission(v_required_permission))
  then
    if new.created_by is distinct from old.created_by
       or new.created_at is distinct from old.created_at then
      raise exception '작성자와 생성일은 변경할 수 없습니다.' using errcode = '42501';
    end if;
  end if;

  return new;
end;
$$;

revoke all on function private.protect_creator_identity()
from public, anon, authenticated;

drop policy if exists events_member_insert on public.events;
create policy events_member_insert
on public.events for insert to authenticated
with check (
  private.is_approved_member()
  and created_by = (select auth.uid())
  and organizer_id = (select auth.uid())
  and exists (
    select 1 from public.activity_categories category
    where category.id = category_id and category.is_active
  )
  and (
    series_id is null
    or (
      (
        private.has_admin_permission('community')
        or private.is_category_manager(category_id)
      )
      and exists (
        select 1 from public.event_series series
        where series.id = series_id
          and series.category_id = category_id
      )
    )
  )
);

drop policy if exists events_owner_manager_update on public.events;
create policy events_owner_manager_update
on public.events for update to authenticated
using (
  private.is_approved_member()
  and (
    (series_id is null and organizer_id = (select auth.uid()))
    or private.has_admin_permission('community')
    or private.is_category_manager(category_id)
  )
)
with check (
  private.is_approved_member()
  and (
    (series_id is null and organizer_id = (select auth.uid()))
    or private.has_admin_permission('community')
    or private.is_category_manager(category_id)
  )
);

create or replace function private.enforce_event_management_boundary()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_user_id uuid := auth.uid();
  v_is_organizer boolean;
  v_is_community_manager boolean;
  v_organizer_transfer_allowed boolean := coalesce(
    current_setting('app.allow_event_organizer_transfer', true),
    'false'
  ) = 'true';
begin
  if v_user_id is null then
    return new;
  end if;

  if new.created_by is distinct from old.created_by then
    raise exception '최초 등록자는 변경할 수 없습니다.' using errcode = '42501';
  end if;

  if new.organizer_id is distinct from old.organizer_id
     and not v_organizer_transfer_allowed then
    raise exception '주최자는 주최자 변경 기능을 통해서만 변경할 수 있습니다.' using errcode = '42501';
  end if;

  if new.created_at is distinct from old.created_at then
    raise exception '생성일은 변경할 수 없습니다.' using errcode = '42501';
  end if;

  if new.series_id is distinct from old.series_id then
    raise exception '반복 활동 연결은 생성 후 변경할 수 없습니다.' using errcode = '42501';
  end if;

  if old.series_id is not null
     and new.category_id is distinct from old.category_id then
    raise exception '반복 활동 일정의 카테고리는 개별 변경할 수 없습니다.'
      using errcode = '42501';
  end if;

  if new.category_id is distinct from old.category_id and not exists (
    select 1 from public.activity_categories category
    where category.id = new.category_id and category.is_active
  ) then
    raise exception '활성 카테고리만 선택할 수 있습니다.' using errcode = '42501';
  end if;

  v_is_organizer := old.series_id is null and old.organizer_id = v_user_id;
  v_is_community_manager := private.has_admin_permission('community');

  if v_is_community_manager then
    return new;
  end if;

  if old.series_id is not null then
    if not private.is_category_manager(old.category_id) then
      raise exception '반복 활동 일정은 해당 카테고리 담당자만 변경할 수 있습니다.'
        using errcode = '42501';
    end if;
    return new;
  end if;

  if v_is_organizer then
    if new.status is distinct from old.status and new.status <> 'cancelled' then
      raise exception '활동 주최자는 일정 취소 외의 상태를 변경할 수 없습니다.' using errcode = '42501';
    end if;
    return new;
  end if;

  if not private.is_category_manager(old.category_id)
     or not private.is_category_manager(new.category_id) then
    raise exception '담당 중인 카테고리 안에서만 다른 회원의 활동을 변경할 수 있습니다.'
      using errcode = '42501';
  end if;

  return new;
end;
$$;

revoke all on function private.enforce_event_management_boundary()
from public, anon, authenticated;

create or replace function private.enforce_member_activity_terminal_read_only()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_user_id uuid := auth.uid();
begin
  if v_user_id is null then
    return new;
  end if;

  if old.series_id is null
     and old.organizer_id = v_user_id
     and old.status in ('cancelled', 'completed')
     and not private.has_admin_permission('community')
     and not private.is_category_manager(old.category_id) then
    raise exception '취소되거나 완료된 활동은 주최자가 수정할 수 없습니다.' using errcode = '42501';
  end if;

  return new;
end;
$$;

revoke all on function private.enforce_member_activity_terminal_read_only()
from public, anon, authenticated;

create or replace function public.join_event(p_event_id bigint)
returns text
language plpgsql
security definer
set search_path = ''
as $$
declare
    v_user_id uuid := auth.uid();
    v_event public.events%rowtype;
    v_existing_status text;
    v_joined_count integer;
    v_new_status text;
    v_actor_name text;
begin
    if v_user_id is null or not private.is_approved_member() then
        raise exception '승인된 회원만 활동에 참여할 수 있습니다.' using errcode = '42501';
    end if;

    select e.* into v_event from public.events as e
    where e.id = p_event_id for update;
    if not found then
        raise exception '활동을 찾을 수 없습니다.' using errcode = 'P0002';
    end if;
    if v_event.status <> 'scheduled' then
        raise exception '현재 참여 신청을 받을 수 없는 활동입니다.' using errcode = '23514';
    end if;
    if now() > v_event.registration_deadline then
        raise exception '참여 신청이 마감되었습니다.' using errcode = '23514';
    end if;

    select ep.status into v_existing_status
    from public.event_participants as ep
    where ep.event_id = p_event_id and ep.user_id = v_user_id for update;
    if found and v_existing_status in ('joined', 'waitlisted') then
        raise exception '이미 참여 또는 대기 신청한 활동입니다.' using errcode = '23505';
    end if;

    select count(*)::integer into v_joined_count
    from public.event_participants as ep
    where ep.event_id = p_event_id and ep.status = 'joined';
    v_new_status := case
        when v_event.capacity is null or v_joined_count < v_event.capacity then 'joined'
        else 'waitlisted'
    end;

    insert into public.event_participants (
        event_id, user_id, status, joined_at, waitlisted_at, cancelled_at
    ) values (
        p_event_id, v_user_id, v_new_status,
        case when v_new_status = 'joined' then now() else null end,
        case when v_new_status = 'waitlisted' then now() else null end,
        null
    )
    on conflict (event_id, user_id) do update
    set status = excluded.status,
        joined_at = excluded.joined_at,
        waitlisted_at = excluded.waitlisted_at,
        cancelled_at = null;

    if v_event.organizer_id <> v_user_id then
        select coalesce(nullif(btrim(p.display_name), ''), '회원') into v_actor_name
        from public.profiles as p where p.id = v_user_id;
        insert into public.notifications (
            user_id, notification_type, kind, title, body, event_id, target_path
        ) values (
            v_event.organizer_id,
            case when v_new_status = 'joined' then 'event_participant_joined' else 'event_participant_waitlisted' end,
            case when v_new_status = 'joined' then 'event_participant_joined' else 'event_participant_waitlisted' end,
            case when v_new_status = 'joined' then '새로운 활동 참여' else '새로운 대기 신청' end,
            case when v_new_status = 'joined'
                then format('%s님이 ''%s'' 활동에 참여했습니다.', v_actor_name, v_event.title)
                else format('%s님이 ''%s'' 활동에 대기 신청했습니다.', v_actor_name, v_event.title)
            end,
            p_event_id,
            format('#/activities/%s', p_event_id)
        );
    end if;
    return v_new_status;
end;
$$;

create or replace function public.cancel_event_participation(p_event_id bigint)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
    v_user_id uuid := auth.uid();
    v_event public.events%rowtype;
    v_current_status text;
    v_promoted_user_id uuid;
    v_joined_count integer;
    v_actor_name text;
begin
    if v_user_id is null or not private.is_approved_member() then
        raise exception '승인된 회원만 참여를 취소할 수 있습니다.' using errcode = '42501';
    end if;

    select e.* into v_event
    from public.events as e
    where e.id = p_event_id
    for update;

    if not found then
        raise exception '활동을 찾을 수 없습니다.' using errcode = 'P0002';
    end if;

    if v_event.status not in ('scheduled', 'closed') then
        raise exception '현재 참여 취소를 처리할 수 없는 활동입니다.' using errcode = '23514';
    end if;

    if now() > v_event.registration_deadline then
        raise exception '참여 취소 가능 시간이 지났습니다.' using errcode = '23514';
    end if;

    select ep.status into v_current_status
    from public.event_participants as ep
    where ep.event_id = p_event_id
      and ep.user_id = v_user_id
    for update;

    if not found or v_current_status = 'cancelled' then
        raise exception '취소할 참여 정보가 없습니다.' using errcode = 'P0002';
    end if;

    if v_event.series_id is null
       and v_event.organizer_id = v_user_id
       and v_current_status = 'joined'
       and exists (
           select 1
           from public.event_participants as other_participant
           where other_participant.event_id = p_event_id
             and other_participant.user_id <> v_user_id
             and other_participant.status = 'joined'
       ) then
        raise exception '다른 참여자가 있는 활동의 주최자는 먼저 주최자를 변경해야 합니다.'
            using errcode = '23514';
    end if;

    update public.event_participants
    set status = 'cancelled', cancelled_at = now()
    where event_id = p_event_id
      and user_id = v_user_id;

    if v_event.organizer_id <> v_user_id then
        select coalesce(nullif(btrim(p.display_name), ''), '회원') into v_actor_name
        from public.profiles as p
        where p.id = v_user_id;

        insert into public.notifications (
            user_id, notification_type, kind, title, body, event_id, target_path
        ) values (
            v_event.organizer_id,
            'event_participation_cancelled',
            'event_participation_cancelled',
            '활동 참여 취소',
            format('%s님이 ''%s'' 활동 참여를 취소했습니다.', v_actor_name, v_event.title),
            p_event_id,
            format('#/activities/%s', p_event_id)
        );
    end if;

    if v_current_status = 'joined' then
        select count(*)::integer into v_joined_count
        from public.event_participants as ep
        where ep.event_id = p_event_id
          and ep.status = 'joined';

        if v_event.capacity is null or v_joined_count < v_event.capacity then
            select ep.user_id into v_promoted_user_id
            from public.event_participants as ep
            where ep.event_id = p_event_id
              and ep.status = 'waitlisted'
            order by ep.waitlisted_at asc, ep.created_at asc
            for update skip locked
            limit 1;

            if v_promoted_user_id is not null then
                update public.event_participants
                set status = 'joined',
                    joined_at = now(),
                    waitlisted_at = null,
                    cancelled_at = null
                where event_id = p_event_id
                  and user_id = v_promoted_user_id;

                insert into public.notifications (
                    user_id, notification_type, title, body, event_id
                ) values (
                    v_promoted_user_id,
                    'waitlist_promoted',
                    '활동 참여가 확정되었어요',
                    format('대기 중이던 "%s" 활동에 참여할 수 있게 되었습니다.', v_event.title),
                    p_event_id
                );
            end if;
        end if;
    end if;
end;
$$;

create or replace function public.remove_or_cancel_event(p_event_id bigint)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_event public.events%rowtype;
  v_user_id uuid := auth.uid();
begin
  if v_user_id is null or not private.is_approved_member() then
    raise exception '승인된 회원만 활동을 관리할 수 있습니다.' using errcode = '42501';
  end if;

  select * into v_event
  from public.events
  where id = p_event_id
  for update;

  if not found then
    raise exception '활동을 찾을 수 없습니다.' using errcode = 'P0002';
  end if;

  if not (
    private.has_admin_permission('community')
    or private.is_category_manager(v_event.category_id)
    or (
      v_event.series_id is null
      and v_event.organizer_id = v_user_id
      and v_event.status in ('scheduled', 'closed')
    )
  ) then
    raise exception '이 활동을 삭제할 권한이 없습니다.' using errcode = '42501';
  end if;

  if v_event.series_id is not null or exists (
    select 1 from public.event_participants participant
    where participant.event_id = p_event_id
      and participant.user_id <> v_event.organizer_id
  ) or exists (
    select 1 from public.notifications notification
    where notification.event_id = p_event_id
      and notification.notification_type <> 'new_activity'
  ) or exists (
    select 1 from public.date_polls poll
    where poll.result_event_id = p_event_id
  ) then
    if v_event.status <> 'cancelled' then
      update public.events set status = 'cancelled' where id = p_event_id;
    end if;
    return jsonb_build_object('action', 'cancelled', 'event_id', p_event_id);
  end if;

  delete from public.events where id = p_event_id;
  return jsonb_build_object('action', 'deleted', 'event_id', p_event_id);
end;
$$;

create or replace function public.transfer_event_organizer(
    p_event_id bigint,
    p_new_organizer_id uuid,
    p_leave_current boolean default false
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
    v_user_id uuid := auth.uid();
    v_event public.events%rowtype;
    v_new_organizer_status text;
begin
    if v_user_id is null or not private.is_approved_member() then
        raise exception '승인된 회원만 주최자를 변경할 수 있습니다.' using errcode = '42501';
    end if;

    select e.* into v_event
    from public.events as e
    where e.id = p_event_id
    for update;

    if not found then
        raise exception '활동을 찾을 수 없습니다.' using errcode = 'P0002';
    end if;

    if v_event.series_id is not null then
        raise exception '반복 활동 일정의 주최자는 개별 변경할 수 없습니다.' using errcode = '23514';
    end if;

    if v_event.status not in ('scheduled', 'closed') then
        raise exception '현재 상태에서는 주최자를 변경할 수 없습니다.' using errcode = '23514';
    end if;

    if v_event.organizer_id <> v_user_id then
        raise exception '현재 주최자만 주최자를 변경할 수 있습니다.' using errcode = '42501';
    end if;

    if p_new_organizer_id is null or p_new_organizer_id = v_user_id then
        raise exception '다른 참여자를 새 주최자로 선택해주세요.' using errcode = '23514';
    end if;

    select ep.status into v_new_organizer_status
    from public.event_participants as ep
    where ep.event_id = p_event_id
      and ep.user_id = p_new_organizer_id
    for update;

    if not found or v_new_organizer_status <> 'joined' then
        raise exception '현재 참여 중인 회원에게만 주최자를 넘길 수 있습니다.' using errcode = '23514';
    end if;

    perform set_config('app.allow_event_organizer_transfer', 'true', true);
    perform set_config(
      'app.event_organizer_previous_leaves',
      case when p_leave_current then 'true' else 'false' end,
      true
    );

    update public.events
    set organizer_id = p_new_organizer_id
    where id = p_event_id;

    perform set_config('app.allow_event_organizer_transfer', 'false', true);
    perform set_config('app.event_organizer_previous_leaves', 'false', true);

    if p_leave_current then
        perform public.cancel_event_participation(p_event_id);
    end if;

    return jsonb_build_object(
        'event_id', p_event_id,
        'creator_id', v_event.created_by,
        'previous_organizer_id', v_user_id,
        'organizer_id', p_new_organizer_id,
        'left_activity', p_leave_current
    );
end;
$$;

revoke all on function public.join_event(bigint) from public, anon, authenticated;
grant execute on function public.join_event(bigint) to authenticated, service_role;
revoke all on function public.cancel_event_participation(bigint) from public, anon, authenticated;
grant execute on function public.cancel_event_participation(bigint) to authenticated, service_role;
revoke all on function public.remove_or_cancel_event(bigint) from public, anon, authenticated;
grant execute on function public.remove_or_cancel_event(bigint) to authenticated, service_role;
revoke all on function public.transfer_event_organizer(bigint, uuid, boolean) from public, anon, authenticated;
grant execute on function public.transfer_event_organizer(bigint, uuid, boolean) to authenticated, service_role;

notify pgrst, 'reload schema';

commit;
