begin;

alter table public.notifications drop constraint if exists notifications_notification_type_check;
alter table public.notifications add constraint notifications_notification_type_check
  check (notification_type = any (array[
    'event_updated'::text,
    'event_cancelled'::text,
    'waitlist_promoted'::text,
    'poll_closed'::text,
    'new_activity'::text,
    'direct_message'::text,
    'activity_reminder'::text,
    'event_participant_joined'::text,
    'event_participant_waitlisted'::text,
    'event_participation_cancelled'::text,
    'join_request_received'::text,
    'service_notice'::text,
    'event_organizer_transfer_requested'::text,
    'event_organizer_transferred'::text
  ]));

create table if not exists public.event_organizer_transfer_requests (
  id bigint generated by default as identity primary key,
  event_id bigint not null references public.events(id) on delete cascade,
  from_organizer_id uuid not null references public.profiles(id),
  to_organizer_id uuid not null references public.profiles(id),
  status text not null default 'pending'
    check (status in ('pending', 'accepted', 'rejected', 'cancelled')),
  leave_current_after_accept boolean not null default false,
  requested_at timestamptz not null default now(),
  responded_at timestamptz,
  cancelled_at timestamptz,
  check (from_organizer_id <> to_organizer_id)
);

create unique index if not exists event_organizer_transfer_requests_one_pending
  on public.event_organizer_transfer_requests(event_id)
  where status = 'pending';

create index if not exists idx_event_organizer_transfer_requests_target
  on public.event_organizer_transfer_requests(to_organizer_id, status, requested_at desc);

alter table public.event_organizer_transfer_requests enable row level security;
revoke all on table public.event_organizer_transfer_requests from public, anon, authenticated;
grant select on table public.event_organizer_transfer_requests to service_role;

create or replace function public.list_event_organizer_history(p_event_id bigint)
returns table (
  id bigint,
  previous_organizer_id uuid,
  previous_organizer_name text,
  organizer_id uuid,
  organizer_name text,
  changed_by uuid,
  changed_by_name text,
  previous_organizer_left boolean,
  changed_at timestamptz
)
language plpgsql
stable
security definer
set search_path = ''
as $$
begin
  if auth.uid() is null or not private.is_approved_member() then
    raise exception '승인된 회원만 주최자 변경 이력을 확인할 수 있습니다.'
      using errcode = '42501';
  end if;

  if not exists (
    select 1
    from public.events as event
    where event.id = p_event_id
  ) then
    raise exception '활동을 찾을 수 없습니다.' using errcode = 'P0002';
  end if;

  return query
  select
    history.id,
    history.previous_organizer_id,
    previous_organizer.display_name as previous_organizer_name,
    history.organizer_id,
    organizer.display_name as organizer_name,
    history.changed_by,
    changed_by.display_name as changed_by_name,
    history.previous_organizer_left,
    history.changed_at
  from public.event_organizer_history as history
  left join public.profiles as previous_organizer
    on previous_organizer.id = history.previous_organizer_id
  left join public.profiles as organizer
    on organizer.id = history.organizer_id
  left join public.profiles as changed_by
    on changed_by.id = history.changed_by
  where history.event_id = p_event_id
    and history.change_type = 'transfer'
  order by history.changed_at desc, history.id desc;
end;
$$;

revoke all on function public.list_event_organizer_history(bigint)
from public, anon, authenticated;
grant execute on function public.list_event_organizer_history(bigint)
to authenticated, service_role;

create or replace function public.get_event_organizer_transfer_request(p_event_id bigint)
returns table (
  id bigint,
  event_id bigint,
  from_organizer_id uuid,
  from_organizer_name text,
  to_organizer_id uuid,
  to_organizer_name text,
  leave_current_after_accept boolean,
  requested_at timestamptz
)
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
  v_user_id uuid := auth.uid();
begin
  if v_user_id is null or not private.is_approved_member() then
    raise exception '승인된 회원만 주최자 변경 요청을 확인할 수 있습니다.'
      using errcode = '42501';
  end if;

  return query
  select
    request.id,
    request.event_id,
    request.from_organizer_id,
    from_organizer.display_name,
    request.to_organizer_id,
    to_organizer.display_name,
    request.leave_current_after_accept,
    request.requested_at
  from public.event_organizer_transfer_requests as request
  left join public.profiles as from_organizer
    on from_organizer.id = request.from_organizer_id
  left join public.profiles as to_organizer
    on to_organizer.id = request.to_organizer_id
  where request.event_id = p_event_id
    and request.status = 'pending'
    and v_user_id in (request.from_organizer_id, request.to_organizer_id)
  limit 1;
end;
$$;

revoke all on function public.get_event_organizer_transfer_request(bigint)
from public, anon, authenticated;
grant execute on function public.get_event_organizer_transfer_request(bigint)
to authenticated, service_role;

create or replace function public.request_event_organizer_transfer(
  p_event_id bigint,
  p_new_organizer_id uuid,
  p_leave_current boolean default false
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_user_id uuid := auth.uid();
  v_event public.events%rowtype;
  v_new_organizer_status text;
  v_request_id bigint;
begin
  if v_user_id is null or not private.is_approved_member() then
    raise exception '승인된 회원만 주최자 변경을 요청할 수 있습니다.' using errcode = '42501';
  end if;

  select e.* into v_event
  from public.events as e
  where e.id = p_event_id
  for update;

  if not found then
    raise exception '활동을 찾을 수 없습니다.' using errcode = 'P0002';
  end if;
  if v_event.series_id is not null then
    raise exception '반복 활동 일정의 주최자는 개별 변경할 수 없습니다.' using errcode = '23514';
  end if;
  if v_event.status not in ('scheduled', 'closed') then
    raise exception '현재 상태에서는 주최자 변경을 요청할 수 없습니다.' using errcode = '23514';
  end if;
  if v_event.organizer_id <> v_user_id then
    raise exception '현재 주최자만 주최자 변경을 요청할 수 있습니다.' using errcode = '42501';
  end if;
  if p_new_organizer_id is null or p_new_organizer_id = v_user_id then
    raise exception '다른 참여자를 새 주최자로 선택해주세요.' using errcode = '23514';
  end if;

  if exists (
    select 1
    from public.event_organizer_transfer_requests as request
    where request.event_id = p_event_id
      and request.status = 'pending'
  ) then
    raise exception '이미 응답을 기다리는 주최자 변경 요청이 있습니다.' using errcode = '23505';
  end if;

  select ep.status into v_new_organizer_status
  from public.event_participants as ep
  where ep.event_id = p_event_id
    and ep.user_id = p_new_organizer_id
  for update;

  if not found or v_new_organizer_status <> 'joined' then
    raise exception '현재 참여 중인 회원에게만 주최자 변경을 요청할 수 있습니다.' using errcode = '23514';
  end if;

  insert into public.event_organizer_transfer_requests (
    event_id,
    from_organizer_id,
    to_organizer_id,
    status,
    leave_current_after_accept
  ) values (
    p_event_id,
    v_user_id,
    p_new_organizer_id,
    'pending',
    p_leave_current
  )
  returning id into v_request_id;

  insert into public.notifications (
    user_id,
    notification_type,
    kind,
    title,
    body,
    event_id,
    target_path
  ) values (
    p_new_organizer_id,
    'event_organizer_transfer_requested',
    'event_organizer_transfer_requested',
    '주최자 변경 요청이 도착했어요',
    format('''%s'' 활동의 주최자를 맡아달라는 요청이 도착했습니다.', v_event.title),
    p_event_id,
    format('#/activities/%s', p_event_id)
  );

  return jsonb_build_object(
    'request_id', v_request_id,
    'event_id', p_event_id,
    'from_organizer_id', v_user_id,
    'to_organizer_id', p_new_organizer_id,
    'status', 'pending',
    'leave_current_after_accept', p_leave_current
  );
end;
$$;

create or replace function public.transfer_event_organizer(
  p_event_id bigint,
  p_new_organizer_id uuid,
  p_leave_current boolean default false
)
returns jsonb
language sql
security definer
set search_path = ''
as $$
  select public.request_event_organizer_transfer(
    p_event_id,
    p_new_organizer_id,
    p_leave_current
  );
$$;

create or replace function public.respond_event_organizer_transfer(
  p_request_id bigint,
  p_accept boolean
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_user_id uuid := auth.uid();
  v_request public.event_organizer_transfer_requests%rowtype;
  v_event public.events%rowtype;
  v_current_status text;
  v_joined_count integer;
  v_promoted_user_id uuid;
begin
  if v_user_id is null or not private.is_approved_member() then
    raise exception '승인된 회원만 주최자 변경 요청에 응답할 수 있습니다.' using errcode = '42501';
  end if;

  select request.* into v_request
  from public.event_organizer_transfer_requests as request
  where request.id = p_request_id
  for update;

  if not found then
    raise exception '주최자 변경 요청을 찾을 수 없습니다.' using errcode = 'P0002';
  end if;
  if v_request.status <> 'pending' then
    raise exception '이미 처리된 주최자 변경 요청입니다.' using errcode = '23514';
  end if;
  if v_request.to_organizer_id <> v_user_id then
    raise exception '요청을 받은 회원만 응답할 수 있습니다.' using errcode = '42501';
  end if;

  select event.* into v_event
  from public.events as event
  where event.id = v_request.event_id
  for update;

  if not found then
    raise exception '활동을 찾을 수 없습니다.' using errcode = 'P0002';
  end if;
  if v_event.organizer_id <> v_request.from_organizer_id then
    raise exception '현재 주최자가 변경되어 이 요청을 처리할 수 없습니다.' using errcode = '23514';
  end if;

  if not p_accept then
    update public.event_organizer_transfer_requests
    set status = 'rejected', responded_at = now()
    where id = p_request_id;

    return jsonb_build_object(
      'request_id', p_request_id,
      'event_id', v_request.event_id,
      'status', 'rejected'
    );
  end if;

  if v_event.series_id is not null or v_event.status not in ('scheduled', 'closed') then
    raise exception '현재 상태에서는 주최자 변경 요청을 수락할 수 없습니다.' using errcode = '23514';
  end if;

  select ep.status into v_current_status
  from public.event_participants as ep
  where ep.event_id = v_request.event_id
    and ep.user_id = v_user_id
  for update;

  if not found or v_current_status <> 'joined' then
    raise exception '현재 활동에 참여 중인 경우에만 주최자 요청을 수락할 수 있습니다.' using errcode = '23514';
  end if;

  perform set_config('app.allow_event_organizer_transfer', 'true', true);
  perform set_config(
    'app.event_organizer_previous_leaves',
    case when v_request.leave_current_after_accept then 'true' else 'false' end,
    true
  );

  update public.events
  set organizer_id = v_user_id
  where id = v_request.event_id;

  perform set_config('app.allow_event_organizer_transfer', 'false', true);
  perform set_config('app.event_organizer_previous_leaves', 'false', true);

  update public.event_organizer_transfer_requests
  set status = 'accepted', responded_at = now()
  where id = p_request_id;

  if v_request.leave_current_after_accept then
    update public.event_participants
    set status = 'cancelled', cancelled_at = now()
    where event_id = v_request.event_id
      and user_id = v_request.from_organizer_id
      and status = 'joined';

    select count(*)::integer into v_joined_count
    from public.event_participants as ep
    where ep.event_id = v_request.event_id
      and ep.status = 'joined';

    if v_event.capacity is null or v_joined_count < v_event.capacity then
      select ep.user_id into v_promoted_user_id
      from public.event_participants as ep
      where ep.event_id = v_request.event_id
        and ep.status = 'waitlisted'
      order by ep.waitlisted_at asc, ep.created_at asc
      for update skip locked
      limit 1;

      if v_promoted_user_id is not null then
        update public.event_participants
        set status = 'joined',
            joined_at = now(),
            waitlisted_at = null,
            cancelled_at = null
        where event_id = v_request.event_id
          and user_id = v_promoted_user_id;

        insert into public.notifications (
          user_id, notification_type, title, body, event_id, target_path
        ) values (
          v_promoted_user_id,
          'waitlist_promoted',
          '활동 참여가 확정되었어요',
          format('대기 중이던 "%s" 활동에 참여할 수 있게 되었습니다.', v_event.title),
          v_request.event_id,
          format('#/activities/%s', v_request.event_id)
        );
      end if;
    end if;
  end if;

  insert into public.notifications (
    user_id,
    notification_type,
    kind,
    title,
    body,
    event_id,
    target_path
  ) values (
    v_user_id,
    'event_organizer_transferred',
    'event_organizer_transferred',
    '활동 주최자가 되었어요',
    format('''%s'' 활동의 새 주최자가 되었습니다.', v_event.title),
    v_request.event_id,
    format('#/activities/%s', v_request.event_id)
  );

  return jsonb_build_object(
    'request_id', p_request_id,
    'event_id', v_request.event_id,
    'creator_id', v_event.created_by,
    'previous_organizer_id', v_request.from_organizer_id,
    'organizer_id', v_user_id,
    'status', 'accepted',
    'left_activity', v_request.leave_current_after_accept
  );
end;
$$;

create or replace function public.cancel_event_organizer_transfer_request(p_request_id bigint)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_user_id uuid := auth.uid();
  v_request public.event_organizer_transfer_requests%rowtype;
begin
  if v_user_id is null or not private.is_approved_member() then
    raise exception '승인된 회원만 주최자 변경 요청을 취소할 수 있습니다.' using errcode = '42501';
  end if;

  select request.* into v_request
  from public.event_organizer_transfer_requests as request
  where request.id = p_request_id
  for update;

  if not found then
    raise exception '주최자 변경 요청을 찾을 수 없습니다.' using errcode = 'P0002';
  end if;
  if v_request.status <> 'pending' then
    raise exception '이미 처리된 주최자 변경 요청입니다.' using errcode = '23514';
  end if;
  if v_request.from_organizer_id <> v_user_id then
    raise exception '요청한 주최자만 변경 요청을 취소할 수 있습니다.' using errcode = '42501';
  end if;

  update public.event_organizer_transfer_requests
  set status = 'cancelled', cancelled_at = now()
  where id = p_request_id;

  return jsonb_build_object(
    'request_id', p_request_id,
    'event_id', v_request.event_id,
    'status', 'cancelled'
  );
end;
$$;

revoke all on function public.request_event_organizer_transfer(bigint, uuid, boolean)
from public, anon, authenticated;
grant execute on function public.request_event_organizer_transfer(bigint, uuid, boolean)
to authenticated, service_role;

revoke all on function public.transfer_event_organizer(bigint, uuid, boolean)
from public, anon, authenticated;
grant execute on function public.transfer_event_organizer(bigint, uuid, boolean)
to authenticated, service_role;

revoke all on function public.respond_event_organizer_transfer(bigint, boolean)
from public, anon, authenticated;
grant execute on function public.respond_event_organizer_transfer(bigint, boolean)
to authenticated, service_role;

revoke all on function public.cancel_event_organizer_transfer_request(bigint)
from public, anon, authenticated;
grant execute on function public.cancel_event_organizer_transfer_request(bigint)
to authenticated, service_role;

notify pgrst, 'reload schema';

commit;
